#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

POWERLEVEL9K_MODE="nerdfont-complete"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

if [[ -f "${ZDOTDIR:-$HOME}/.powerlevel9krc" ]]; then
  source "${ZDOTDIR:-$HOME}/.powerlevel9krc"
fi
