#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#Base16 Shell
BASE16_SHELL="$HOME/git/base16/base16-shell/scripts/base16-google-dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

export TERM="xterm-256color"

POWERLEVEL9K_MODE="awesome-fontconfig"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status rbenv)
POWERLEVEL9K_STATUS_VERBOSE=false
#POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
#POWERLEVEL9K_SHORTEN_DIR_LENGTH=3

#Truncate directory path:
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_SHORTEN_DELIMITER=""
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"

#Customize segment colors
POWERLEVEL9K_TIME_BACKGROUND='254'
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND='254'
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='black'
POWERLEVEL9K_OS_ICON_BACKGROUND='250'
POWERLEVEL9K_OS_ICON_FOREGROUND=black
#POWERLEVEL9K_STATUS_ERROR_BACKGROUND='238'

#Don't display user at prompt:
#export DEFAULT_USER=$USER

# Source vte.sh
. /etc/profile.d/vte.sh
